USE kiriyena_db;
ALTER TABLE `pardevejs` CHANGE `Izveidosanas_datums` `Izveidosanas_datums` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;

INSERT INTO `kategorija` (`Kategorija_ID`, `Nosaukums_kategorija`, `Kat_attela`) VALUES (NULL, 'Kosmētika', 'uploads/6463d41f2832c0.86656799.png');
INSERT INTO `kategorija` (`Kategorija_ID`, `Nosaukums_kategorija`, `Kat_attela`) VALUES (NULL, 'Apģērbs', 'uploads/6463d4a2925549.14582951.png');
INSERT INTO `kategorija` (`Kategorija_ID`, `Nosaukums_kategorija`, `Kat_attela`) VALUES (NULL, 'Roku darbs', 'uploads/6463db9bd7ec84.50129827.png');

INSERT INTO `k_apakssadala` (`Kapakssadala_ID`, `Nosaukums_sadala`) VALUES (NULL, 'Lūpu krāsas'), (NULL, 'Pildspalvas un kodoloņi');
INSERT INTO `k_apakssadala` (`Kapakssadala_ID`, `Nosaukums_sadala`) VALUES (NULL, 'Pušķi');

INSERT INTO `pardevejs` (`Pardevejs_ID`, `Vards_pardevejs`, `Uzvards_pardevejs`, `E_pasts_pardevejs`, `T_numurs_pardevejs`, `Loma`, `Apraksts`, `Izveidosanas_datums`, `Brenda_nosaukums`, `Attela_URL`, `Parole_pardevejs`) VALUES (NULL, 'Karina', 'Štifurska', 'kstifurska@gmail.com', '+37127079797', 'Pārdevējs', 'Laipni lūdzam mūsu veikalā \"Papīra tauriņi\" - mājīgā vietā, kur dzimst burvīgi pušķi, kas atdzīvina pasaku tēlus! Mēs esam mazs ģimenes bizness, kas specializējas unikālu pušķu izveidē no skaistiem papīra tauriņiem.\r\n\r\nKatrs mūsu pušķis ir radošas procesa rezultāts, kurā mēs apvienojam maigo papīra tekstūru ar izsmalcinātu dizainu. Mēs ar mīlestību un prasmi izgriežam, saliekam un veidojam dažādu izmēru, krāsu un faktūru tauriņus. Katrs tauriņš mūsu pušķos iemieso dabas skaistumu un izsmalcinātību.\r\n\r\nMūsu pušķi ar papīra tauriņiem sniegs prieku un sajūsminājumu jūsu tuviniekiem visos īpašajos dzīves brīžos: dzimšanas dienas, jubilejas, kāzas vai vienkārši kā uzmanības un mīlestības simbols. Tie ir lieliski interjera rotaslietas un ideāls dāvana, kas saglabās savu skaistumu uz ilgu laiku.', 
current_timestamp(), 'KIRIYENA', 'uploads/6463d7d3f0c859.06150434.png', 'c39e63db380e2b0a85356da1c126ebb2');

INSERT INTO `prece` (`Prece_ID`, `Nosaukums_prece`, `Cena`, `Statuss`, `Apraksts_prece`, `Attela_prece`, `Ipatnibas_prece`, `ID_Pardevejs`, `IDKapakssadala`, `ID_Kategorija`) VALUES (NULL, 'Papīra tauriņi', '25.50', 'Ir pieejams', 'Šis skaistais pušķis no papīra tauriņiem ir patiesa mākslas darba izpausme, ko radījis talantīgs cilvēks. Katrs tauriņš šajā pušķī tiek izgriezts ar rokām, rūpīgi salocīts un uzmanīgi nostiprināts.\r\n\r\nKatras tauriņa izgatavošana prasa meistarību, uzmanību pret detaļām un radošu pieeju. Izmantojot dažādus papīra toņus un faktūras, šī pušķa autors veiksmīgi nodod dabiskās tauriņu skaistuma un izsmalcinātības jūtu. Viņš katrā darbā ievieto savu aizrautību un mīlestību pret mākslu, lai rezultātā tiktu radīts unikāls un nenopietojams pušķis.\r\n\r\nŠis pušķis no papīra tauriņiem nav tikai skaista dekorācija, bet arī maiguma, elegances un iedvesmas simbols. Tas būs lielisks dāvana īpašiem dzīves brīžiem - dzimšanas dienai, jubilejai, kāzām vai vienkārši kā simbols uzmanībai un mīlestībai pret tuvajām personām.', 'uploads/6463de967a0af8.78003787.jpg', '\r\nŠī pušķa trīs izcelšanās īpašības ir šādas:\r\n\r\nIndividualitāte: Šis pušķis no būmaļiem piedāvā klientam iespēju izvēlēties krāsu, kas viņam vislabāk patīk vai atbilst konkrētajai situācijai. Tas dod iespēju pielāgot pušķa izskatu un saskaņot to ar personiskajām vēlmēm vai notikuma tematiku.\r\n\r\nMāksliniecisks dizains: Katrs būmaļu pušķa elements ir rūpīgi izstrādāts, lai radītu skaisti izkārtojumu un harmoniju. Kombinējot dažādus būmaļu veidus, krāsas un izmērus, pušķis iegūst unikālu māksliniecisku izskatu, kas piesaista uzmanību un iepriecina acis.\r\n\r\nDabiskums un ilgstošība: Būmaļi ir dabiski un ilgstoši materiāli, kas nodrošina, ka šis pušķis saglabās savu skaistumu un svaigumu ilgāku laiku. Tas ir lielisks veids, kā izteikt mīlestību un rūpes, dāvinot kaut ko dabisku un ilgstošu saviem tuviniekiem vai sev.', '1', '3', '3');

